@file:JvmName("DexKit")

package io.github.s1ddhants1.swiftbackupprem

data class VersionClasses(
    val clientId: String,
    val homeViewModel: String,
    val authUser: String,
    val anonUser: String,
    val oauthHelper: String? = null,
    val authRequestBuilder: String? = null,
    val appBackup: String? = null,
    val appMetadataXml: String? = null,
    val firebaseWatcher: String? = null,
    val fireSynchronizer: String? = null,
    val fireSynchronizerSuccess: String? = null,
    val customClassMapper: String? = null,
    val settingsFragment: String? = null,
    val settingsDetailFragment: String? = null,
    val baseSettingsFragment: String? = null,
    val rootServiceManager: String? = null
)

val versionMap = mapOf(
    525 to VersionClasses(
        clientId = "ve.r0",
        homeViewModel = "tf.q",
        authUser = "org.swiftapps.swiftbackup.common.b1",
        anonUser = "yd.b",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "sg.t",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "sg.d",
    ),
    527 to VersionClasses(
        clientId = "ve.r0",
        homeViewModel = "tf.q",
        authUser = "org.swiftapps.swiftbackup.common.b1",
        anonUser = "yd.b",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "sg.t",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "sg.d",
    ),
    529 to VersionClasses(
        clientId = "ve.r0",
        homeViewModel = "tf.q",
        authUser = "org.swiftapps.swiftbackup.common.b1",
        anonUser = "yd.b",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "sg.t",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "sg.d",
    ),
    532 to VersionClasses(
        clientId = "se.s0",
        homeViewModel = "qf.q",
        authUser = "org.swiftapps.swiftbackup.common.a1",
        anonUser = "vd.b",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "pg.u",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "pg.d",
    ),
    533 to VersionClasses(
        clientId = "se.s0",
        homeViewModel = "qf.q",
        authUser = "org.swiftapps.swiftbackup.common.a1",
        anonUser = "vd.b",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "pg.u",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "pg.d",
    ),
    536 to VersionClasses(
        clientId = "qf.s0",
        homeViewModel = "og.q",
        authUser = "org.swiftapps.swiftbackup.common.a1",
        anonUser = "te.b",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "nh.u",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "nh.d",
    ),
    538 to VersionClasses(
        clientId = "qf.s0",
        homeViewModel = "og.q",
        authUser = "org.swiftapps.swiftbackup.common.a1",
        anonUser = "te.b",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "nh.u",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "nh.d",
    ),
    540 to VersionClasses(
        clientId = "qf.s0",
        homeViewModel = "og.q",
        authUser = "org.swiftapps.swiftbackup.common.a1",
        anonUser = "te.b",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "nh.u",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "nh.d",
    ),
    542 to VersionClasses(
        clientId = "qf.s0",
        homeViewModel = "og.q",
        authUser = "org.swiftapps.swiftbackup.common.a1",
        anonUser = "te.b",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "nh.u",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "nh.d",
    ),
    545 to VersionClasses(
        clientId = "rf.s0",
        homeViewModel = "pg.q",
        authUser = "org.swiftapps.swiftbackup.common.z0",
        anonUser = "ue.b",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "oh.y",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "oh.h",
    ),
    547 to VersionClasses(
        clientId = "rf.s0",
        homeViewModel = "pg.q",
        authUser = "org.swiftapps.swiftbackup.common.z0",
        anonUser = "ue.b",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "oh.y",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "oh.h",
    ),
    555 to VersionClasses(
        clientId = "kf.s0",
        homeViewModel = "ig.q",
        authUser = "org.swiftapps.swiftbackup.common.z0",
        anonUser = "ne.b",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "hh.y",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "hh.h",
    ),
    557 to VersionClasses(
        clientId = "kf.s0",
        homeViewModel = "ig.q",
        authUser = "org.swiftapps.swiftbackup.common.z0",
        anonUser = "ne.b",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "hh.y",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "hh.h",
    ),
    558 to VersionClasses(
        clientId = "kf.s0",
        homeViewModel = "ig.q",
        authUser = "org.swiftapps.swiftbackup.common.z0",
        anonUser = "ne.b",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "hh.y",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "hh.h",
    ),
    561 to VersionClasses(
        clientId = "kf.s0",
        homeViewModel = "ig.q",
        authUser = "org.swiftapps.swiftbackup.common.z0",
        anonUser = "ne.b",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "hh.y",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "hh.h",
    ),
    566 to VersionClasses(
        clientId = "sf.r0",
        homeViewModel = "qg.p",
        authUser = "org.swiftapps.swiftbackup.common.k1",
        anonUser = "ve.b",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "ph.y",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "ph.h",
        rootServiceManager = "com.topjohnwu.superuser.internal.RootServiceManager",
    ),
    569 to VersionClasses(
        clientId = "rf.r0",
        homeViewModel = "pg.p",
        authUser = "org.swiftapps.swiftbackup.common.k1",
        anonUser = "ue.b",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "oh.y",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "oh.h",
        rootServiceManager = "com.topjohnwu.superuser.internal.RootServiceManager",
    ),
    584 to VersionClasses(
        clientId = "eh.u",
        homeViewModel = "org.swiftapps.swiftbackup.home.b",
        authUser = "org.swiftapps.swiftbackup.common.z0",
        anonUser = "org.swiftapps.swiftbackup.anonymous.a",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "org.swiftapps.swiftbackup.settings.p",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "bj.g",
        rootServiceManager = "com.topjohnwu.superuser.internal.RootServiceManager",
    ),
    585 to VersionClasses(
        clientId = "eh.u",
        homeViewModel = "org.swiftapps.swiftbackup.home.b",
        authUser = "org.swiftapps.swiftbackup.common.z0",
        anonUser = "org.swiftapps.swiftbackup.anonymous.a",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "org.swiftapps.swiftbackup.settings.p",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "bj.g",
        rootServiceManager = "com.topjohnwu.superuser.internal.RootServiceManager",
    ),
    587 to VersionClasses(
        clientId = "eh.u",
        homeViewModel = "org.swiftapps.swiftbackup.home.b",
        authUser = "org.swiftapps.swiftbackup.common.z0",
        anonUser = "org.swiftapps.swiftbackup.anonymous.a",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "org.swiftapps.swiftbackup.settings.p",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "bj.g",
        rootServiceManager = "com.topjohnwu.superuser.internal.RootServiceManager",
    ),
    588 to VersionClasses(
        clientId = "eh.u",
        homeViewModel = "org.swiftapps.swiftbackup.home.b",
        authUser = "org.swiftapps.swiftbackup.common.z0",
        anonUser = "org.swiftapps.swiftbackup.anonymous.a",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "org.swiftapps.swiftbackup.settings.p",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "bj.g",
        rootServiceManager = "com.topjohnwu.superuser.internal.RootServiceManager",
    ),
    590 to VersionClasses(
        clientId = "eh.u",
        homeViewModel = "org.swiftapps.swiftbackup.home.b",
        authUser = "org.swiftapps.swiftbackup.common.z0",
        anonUser = "org.swiftapps.swiftbackup.anonymous.a",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        fireSynchronizer = "org.swiftapps.swiftbackup.common.q0",
        fireSynchronizerSuccess = "org.swiftapps.swiftbackup.common.q0\$a\$b",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "org.swiftapps.swiftbackup.settings.p",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "bj.g",
        rootServiceManager = "com.topjohnwu.superuser.internal.RootServiceManager",
    ),
    596 to VersionClasses(
        clientId = "p8.u",
        homeViewModel = "org.swiftapps.swiftbackup.home.b",
        authUser = "org.swiftapps.swiftbackup.common.a0",
        anonUser = "org.swiftapps.swiftbackup.anonymous.a",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        fireSynchronizer = "org.swiftapps.swiftbackup.common.P",
        fireSynchronizerSuccess = "org.swiftapps.swiftbackup.common.P\$a\$b",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "org.swiftapps.swiftbackup.settings.p",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "m9.g",
        rootServiceManager = "com.topjohnwu.superuser.internal.RootServiceManager",
    ),
    598 to VersionClasses(
        clientId = "p8.u",
        homeViewModel = "org.swiftapps.swiftbackup.home.b",
        authUser = "org.swiftapps.swiftbackup.common.a0",
        anonUser = "org.swiftapps.swiftbackup.anonymous.a",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        fireSynchronizer = "org.swiftapps.swiftbackup.common.P",
        fireSynchronizerSuccess = "org.swiftapps.swiftbackup.common.P\$a\$b",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "org.swiftapps.swiftbackup.settings.p",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "m9.g",
        rootServiceManager = "com.topjohnwu.superuser.internal.RootServiceManager",
    ),
    601 to VersionClasses(
        clientId = "pi.o2",
        homeViewModel = "org.swiftapps.swiftbackup.home.a",
        authUser = "org.swiftapps.swiftbackup.common.a3",
        anonUser = "org.swiftapps.swiftbackup.anonymous.a",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        fireSynchronizer = "org.swiftapps.swiftbackup.common.b2",
        fireSynchronizerSuccess = "org.swiftapps.swiftbackup.common.b2\$a\$b",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "org.swiftapps.swiftbackup.settings.s",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "qk.r",
        rootServiceManager = "com.topjohnwu.superuser.internal.RootServiceManager",
    ),
    603 to VersionClasses(
        clientId = "pi.o2",
        homeViewModel = "org.swiftapps.swiftbackup.home.a",
        authUser = "org.swiftapps.swiftbackup.common.a3",
        anonUser = "org.swiftapps.swiftbackup.anonymous.a",
        authRequestBuilder = "net.openid.appauth.e",
        firebaseWatcher = "org.swiftapps.swiftbackup.common.FirebaseConnectionWatcher",
        fireSynchronizer = "org.swiftapps.swiftbackup.common.b2",
        fireSynchronizerSuccess = "org.swiftapps.swiftbackup.common.b2\$a\$b",
        customClassMapper = "com.google.firebase.database.core.utilities.encoding.CustomClassMapper",
        settingsFragment = "org.swiftapps.swiftbackup.settings.s",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "qk.r",
        rootServiceManager = "com.topjohnwu.superuser.internal.RootServiceManager",
    ),
    620 to VersionClasses(
        clientId = "defpackage.gn5",
        homeViewModel = "defpackage.c64",
        authUser = "defpackage.d45",
        anonUser = "defpackage.b45",
        oauthHelper = "defpackage.uj",
        authRequestBuilder = "defpackage.c90",
        appBackup = "defpackage.hk",
        appMetadataXml = "defpackage.cu",
        firebaseWatcher = "defpackage.gg3",
        fireSynchronizer = "defpackage.cf3",
        fireSynchronizerSuccess = "defpackage.xe3",
        customClassMapper = "defpackage.t62",
        settingsFragment = "defpackage.pa7",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "defpackage.fm0",
        rootServiceManager = "defpackage.bq6",
    ),
    623 to VersionClasses(
        clientId = "defpackage.gp5",
        homeViewModel = "defpackage.p74",
        authUser = "defpackage.n55",
        anonUser = "defpackage.l55",
        oauthHelper = "defpackage.hp5",
        authRequestBuilder = "defpackage.wj",
        firebaseWatcher = "defpackage.oh3",
        fireSynchronizer = "defpackage.jg3",
        fireSynchronizerSuccess = "defpackage.ag3",
        customClassMapper = "defpackage.a72",
        settingsFragment = "defpackage.bd7",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "defpackage.qm0",
    ),
    626 to VersionClasses(
        clientId = "defpackage.dp5",
        homeViewModel = "defpackage.f74",
        authUser = "defpackage.w55",
        anonUser = "defpackage.u55",
        oauthHelper = "defpackage.fp5",
        authRequestBuilder = "defpackage.rj",
        firebaseWatcher = "defpackage.rh3",
        fireSynchronizer = "defpackage.lg3",
        fireSynchronizerSuccess = "defpackage.cg3",
        customClassMapper = "defpackage.n72",
        settingsFragment = "defpackage.re7",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "defpackage.qm0",
    ),
    628 to VersionClasses(
        clientId = "defpackage.jq5",
        homeViewModel = "defpackage.r84",
        authUser = "defpackage.x65",
        anonUser = "defpackage.v65",
        oauthHelper = "defpackage.kq5",
        authRequestBuilder = "defpackage.uj",
        firebaseWatcher = "defpackage.oi3",
        fireSynchronizer = "defpackage.ih3",
        fireSynchronizerSuccess = "defpackage.yg3",
        customClassMapper = "defpackage.z72",
        settingsFragment = "defpackage.uf7",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "defpackage.um0",
        rootServiceManager = "defpackage.ou6",
    ),
)
