@file:JvmName("DexKit")

package io.github.s1ddhants1.swiftbackupprem

data class VersionClasses(
    val clientId: String,
    val homeViewModel: String,
    val authUser: String,
    val anonUser: String,
    val oauthHelper: String? = null,
    val authRequestBuilder: String? = null,
    val appBackup: String? = null,
    val appMetadataXml: String? = null,
    val firebaseWatcher: String? = null,
    val fireSynchronizer: String? = null,
    val fireSynchronizerSuccess: String? = null,
    val customClassMapper: String? = null,
    val settingsFragment: String? = null,
    val settingsDetailFragment: String? = null,
    val baseSettingsFragment: String? = null,
    val rootServiceManager: String? = null
)

val versionMap = mapOf(
    561 to VersionClasses("kf.s0", "org.swiftapps.swiftbackup.home.a", "org.swiftapps.swiftbackup.common.a3", "org.swiftapps.swiftbackup.anonymous.a"),
    569 to VersionClasses("rf.r0", "org.swiftapps.swiftbackup.home.a", "org.swiftapps.swiftbackup.common.a3", "org.swiftapps.swiftbackup.anonymous.a"),
    590 to VersionClasses("eh.u", "org.swiftapps.swiftbackup.home.a", "org.swiftapps.swiftbackup.common.a3", "org.swiftapps.swiftbackup.anonymous.a"),
    620 to VersionClasses(
        clientId = "defpackage.gn5",
        homeViewModel = "defpackage.c64",
        authUser = "defpackage.d45",
        anonUser = "defpackage.b45",
        oauthHelper = "defpackage.uj",
        authRequestBuilder = "defpackage.c90",
        appBackup = "defpackage.hk",
        appMetadataXml = "defpackage.cu",
        firebaseWatcher = "defpackage.gg3",
        fireSynchronizer = "defpackage.cf3",
        fireSynchronizerSuccess = "defpackage.xe3",
        customClassMapper = "defpackage.t62",
        settingsFragment = "defpackage.pa7",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "defpackage.fm0",
        rootServiceManager = "defpackage.bq6"
    ),
    623 to VersionClasses(
        clientId = "defpackage.gp5",
        homeViewModel = "defpackage.p74",
        authUser = "defpackage.n55",
        anonUser = "defpackage.l55",
        oauthHelper = "defpackage.hp5",
        authRequestBuilder = "defpackage.wj",
        firebaseWatcher = "defpackage.oh3",
        fireSynchronizer = "defpackage.jg3",
        fireSynchronizerSuccess = "defpackage.ag3",
        customClassMapper = "defpackage.a72",
        settingsFragment = "defpackage.bd7",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "defpackage.qm0"
    ),
    626 to VersionClasses(
        clientId = "defpackage.dp5",
        homeViewModel = "defpackage.f74",
        authUser = "defpackage.w55",
        anonUser = "defpackage.u55",
        oauthHelper = "defpackage.fp5",
        authRequestBuilder = "defpackage.rj",
        firebaseWatcher = "defpackage.rh3",
        fireSynchronizer = "defpackage.lg3",
        fireSynchronizerSuccess = "defpackage.cg3",
        customClassMapper = "defpackage.n72",
        settingsFragment = "defpackage.re7",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "defpackage.qm0"
    ),
    628 to VersionClasses(
        clientId = "defpackage.jq5",
        homeViewModel = "defpackage.r84",
        authUser = "defpackage.x65",
        anonUser = "defpackage.v65",
        oauthHelper = "defpackage.kq5",
        authRequestBuilder = "defpackage.uj",
        firebaseWatcher = "defpackage.oi3",
        fireSynchronizer = "defpackage.ih3",
        fireSynchronizerSuccess = "defpackage.yg3",
        customClassMapper = "defpackage.z72",
        settingsFragment = "defpackage.uf7",
        settingsDetailFragment = "org.swiftapps.swiftbackup.settings.a",
        baseSettingsFragment = "defpackage.um0",
    ),
)
